namespace :email_template do
  desc "email template init"

  task :init => :environment do
    email_templates = [
        {name: 'Retailer registration', subject: 'REVV account', body: 'Dear Admin,<br/><br/>#user.company_name has registered for a REVV account. <br/><br/>Please proceed to approve/reject the registration at <a href="http://revv.sg">revv.sg</a>.<br/>', template_type: '1'},
        {name: 'Admin approve Retailer registration', subject: 'REVV account registration has been approved', body: 'Dear #user.company_name,<br/><br/>Congratulations, your REVV account registration has been <b>approved</b>.<br/><br/>You may now log in to your account at <a href="http://revv.sg">revv.sg</a>. <br/>', template_type: '2'},
        {name: 'Admin reject Retailer registration', subject: 'REVV account registration has been rejected', body: 'Dear #user.company_name,<br/><br/>Your REVV account registration has been <b>rejected</b>.<br/>Comments: #user.comment <br/><br/>Kindly access your account registration page at <a href="http://revv.sg">revv.sg</a> for further actions.', template_type: '3'},
        {name: 'Buyer invitation', subject: 'You are invited to participate in an upcoming auction', body: 'Dear #buyer.name,<br/><br/>You are invited to participate in an upcoming auction for aggregated electricity purchase. <br/><br/>Please proceed to view and manage your participation at <a href="http://revv.sg">revv.sg</a>. <br/>', template_type: '4'},
        {name: 'Retailer invitation', subject: 'An auction for aggregated electricity purchase has been published', body: 'Dear #user.company_name,<br/><br/>An auction for aggregated electricity purchase has been published. You are invited to bid in this auction. <br/><br/>Please proceed to view and manage your participation at <a href="http://revv.sg">revv.sg</a>.<br/>', template_type: '5'},
        {name: 'Retailer Dashboard (submit tender documents)', subject: '#user.company_name has submitted their tender documents', body: 'Dear Admin,<br/><br/>#user.company_name has submitted their tender documents. <br/><br/>Please proceed to approve/reject the tender documents submission at <a href="http://revv.sg">revv.sg</a>.<br/>', template_type: '6'},
        {name: 'Retailer Dashboard (Admin approve tender document)', subject: 'Your tender documents submission has been approved', body: 'Dear #user.company_name,<br/><br/>Your tender documents submission has been <b>approved</b>.<br/><br/>You may now log in to your account at <a href="http://revv.sg">revv.sg</a> to submit the contact person details for actual day of bidding. <br/>', template_type: '7'},
        {name: 'Retailer Dashboard (Admin reject tender document)', subject: 'Your tender documents submission has been rejected', body: 'Dear #user.company_name,<br/><br/>Your tender documents submission has been <b>rejected</b>.<br/>Comments: #user.comment <br/><br/>Please log in to your account at <a href="http://revv.sg">revv.sg</a> for further actions.<br/>', template_type: '8'},
        {name: 'Admin responded deviation request', subject:'Admin has responded to your deviation request.', body:'Dear #user.company_name,<br/><br/>Admin has responded to your deviation request.<br/><br/>Please proceed to view the response and manage deviation request at <a href="http://revv.sg">revv.sg</a>.', template_type: '9'},
        {name: 'Auction winner confirmation', subject:'Auction winner confirmation', body:'Dear #retailer_company_name,<br/><br/>Congratulations, #retailer_company_name has been awarded the tender for #months electricity purchase category under the reverse auction conducted on #date_of_ra (ID: #ra_id).<br/><br/>Please proceed to acknowledge the Letter(s) of Award at <a href="http://revv.sg">revv.sg</a>.', template_type: '10'},
        {name: 'Buyer registration', subject:'Buyer registration', body:'Dear Admin,<br/><br/>#buyer_company_name has registered for a REVV account.<br/><br/>Please proceed to manage the registration at <a href="http://revv.sg">revv.sg</a>.', template_type: '11'},
        {name: 'CSV and PDF files upload', subject:'CSV and PDF files upload', body:'Dear #buyer_company_name,<br/><br/>Admin has uploaded the (i) tenant account details and (ii) Master - Tenant Agreement. <br/><br/>Please proceed to accept/reject at <a href="http://revv.sg">revv.sg</a>.', template_type: '12'},
        {name: 'Accept CSV and PDF files', subject:'Accept CSV and PDF files', body:'Dear Admin,<br/><br/>#buyer_company_name has accepted your tenant file uploads.<br/><br/>Comments: #comments<br/><br/>Please proceed to manage the registration at <a href="http://revv.sg">revv.sg</a>.', template_type: '13'},
        {name: 'Reject CSV and PDF files', subject:'Reject CSV and PDF files', body:'Dear Admin,<br/><br/>#buyer_company_name has rejected your tenant file uploads.<br/><br/>Comments: #comments<br/><br/>Please proceed to manage the registration at <a href="http://revv.sg">revv.sg</a>.', template_type: '14'},
        {name: 'Tenant account creation', subject:'Tenant account creation', body:'Dear #tenant_company_name,<br/><br/>A REVV account has been created for you by #buyer_company_name for electricity bill management.<br/><br/>REVV account log-in details:<br/>Email: #tenant_email<br/>Default Password: #password<br/><br/>You may now log in to your account and proceed to change your default passport at <a href="http://revv.sg">revv.sg</a>.', template_type: '15'},
        {name: 'Buyer change tenant information (1)', subject:'Buyer change tenant information(1)', body:'Dear Admin,<br/><br/>#buyer_company_name has raised a change request in the tenant details.<br/><br/>Please proceed to approve/reject the change request at <a href="http://revv.sg">revv.sg</a>.', template_type: '16'},
        {name: 'Buyer change tenant information (2)', subject:'Buyer change tenant information(2)', body:'Dear Admin,<br/><br/>#buyer_company_name has made amendments to the following fields for tenant: #tenant_name<br/>- #field_1<br/>- #field_2<br/><br/>Please log in to your account at <a href="http://revv.sg">revv.sg</a> to view the updated tenant details.', template_type: '17'},
        {name: 'Buyer change tenant information (3)', subject:'Buyer change tenant information(3)', body:'Dear #tenant_company_name],<br/><br/>#buyer_company_name has made amendments to the following fields for tenant: #tenant_name<br/>- #field_1<br/>- #field_2<br/><br/>Please log in to your account at <a href="http://revv.sg">revv.sg</a> to view the updated tenant details.', template_type: '18'},
        {name: 'Admin approve tenant information change', subject:'Admin approve tenant information change', body:'Dear #buyer_company_name],<br/><br/>Your tenant details change request has been approved.<br/><br/>Comments: #comments<br/><br/>Please log in to your account at <a href="http://revv.sg">revv.sg</a> to view the updated tenant details.', template_type: '19'},
        {name: 'Admin reject tenant information change', subject:'Admin reject tenant information change', body:'Dear #buyer_company name,<br/><br/>Your tenant details change request has been rejected.<br/><br/>Comments: #comments<br/><br/>Please log in to your account at <a href="http://revv.sg">revv.sg</a> for further actions.', template_type: '20'},
        {name: 'Tenant change (to Admin)', subject:'Tenant change', body:'Dear Admin,<br/><br/>#tenant_company_name has made amendments to the following fields:<br/>- #field_1<br/>- #field_2<br/><br/>Please log in to your account at <a href="http://revv.sg">revv.sg</a> to view the updated tenant details. ', template_type: '21'},
        {name: 'Tenant change (to Buyer)', subject:'Tenant change', body:'Dear #buyer_company_name,<br/><br/>#tenant_company_name has made amendments to the following fields:<br/>- #field_1<br/>- #field_2<br/><br/>Please log in to your account at <a href="http://revv.sg">revv.sg</a> to view the updated tenant details. ', template_type: '22'},
        {name: 'Admin add new tenant accounts', subject:'Admin add new tenant accounts', body:'Dear #buyer_company_name,<br/><br/>Admin has added new tenant accounts. <br/><br/>Please proceed to accept/reject the new tenant accounts at <a href="http://revv.sg">revv.sg</a>.', template_type: '23'},
        {name: 'Buyer accept new added tenant accounts', subject:'Buyer accept new added tenant accounts', body:'Dear Admin,<br/><br/>#buyer_company_name has accepted the new tenant account details.<br/><br/>Comments: #comments<br/><br/>Please log in to your account at <a href="http://revv.sg">revv.sg</a> to view the updated tenant details.', template_type: '24'},
        {name: 'Buyer reject new added tenant accounts', subject:'Buyer reject new added tenant accounts', body:'Dear Admin,<br/><br/>#buyer_company_name has rejected the new tenant account details.<br/><br/>Comments: #comments<br/><br/>Please log in to your account at <a href="http://revv.sg">revv.sg</a> for further actions.', template_type: '25'},
        {name: "Buyer click 'Participate'", subject:"Buyer click 'Participate'", body:'Dear Admin,<br/><br/>#buyer_company_name has submitted purchase details for participation in an upcoming auction: #name_of_ra on #date_time.<br/><br/>Please proceed to approve/reject the submission at <a href="http://revv.sg">revv.sg</a>', template_type: '26'},
        {name: "Upcoming auction has been approved", subject:"#name_of_ra on #date_time has been approved", body:'Dear #buyer_company_name,<br/><br/>Your purchase details for participation in the upcoming auction (#name_of_ra on #date_time) has been approved.<br/><br/>You may view your approved participation details at <a href="http://revv.sg">revv.sg</a>.', template_type: '27'},
        {name: "Upcoming auction has been rejected", subject:"#name_of_ra on #date_time has been rejected", body:'Dear #buyer_company_name,<br/><br/>Your purchase details for participation in the upcoming auction (#name_of_ra on #date_time) has been rejected.<br/><br/>Please log in to your account at <a href="http://revv.sg">revv.sg</a> for further actions.', template_type: '28'},

    ]

    email_templates.each do |template|
      EmailTemplate.find_or_create_by(template_type: template[:template_type]) do |this_template|
        this_template.name = template[:name]
        this_template.subject = template[:subject]
        this_template.body = template[:body]
        this_template.template_type = template[:template_type]
      end
    end
  end

  task :delete => [:environment] do
    EmailTemplate.delete_all
  end

  task :reset => [:delete, :init]
end
