FROM rawebappregistry.azurecr.io/rails_base:latest
ENV INSTALL_PATH /app
WORKDIR $INSTALL_PATH

ENV RAILS_ENV production
ENV RAILS_SERVE_STATIC_FILES=true    
ARG REDISTOGO_URL
ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
COPY . .

RUN bundle install -j4 && \
    yarn install

RUN chmod -R +x bin
RUN rake db:create
RUN export NODE_OPTIONS=--max-old-space-size=3096 && \
    rails assets:precompile
CMD ["rails", "server", "-b", "0.0.0.0", "-e", "production"]
