apiVersion: v1
data:
  APPENV: prod
  APPNAME: reverse-auction
  HTTPSTUB_CONN_TIMEOUT: 30s
  HTTPSTUB_MAX_TIMEOUT: 90s
  HTTPSTUB_RETRIES: "2"
  LOG_LEVEL: DEBUG
  SMTP_ADDRESS: some_smtp_address
  SMTP_PORT: some_smtp_port
  SECRET_KEY_BASE: something
kind: ConfigMap
metadata:
  name: reverse-auction-configmap
