apiVersion: v1
data:
  APPENV: prod
  APPNAME: reverse-auction
  HTTPSTUB_CONN_TIMEOUT: 30s
  HTTPSTUB_MAX_TIMEOUT: 90s
  HTTPSTUB_RETRIES: "2"
  LOG_LEVEL: DEBUG
  HOSTNAME: something
  SENDGRID_USERNAME: something
  SENDGRID_PASSWORD: something
  MAILER_DEFAULT_FROM: something
  SECRET_KEY_BASE: something
kind: ConfigMap
metadata:
  name: reverse-auction-configmap
