import "atlas/src/index.js";

//import "./javascripts/shared.js";
import "./styles/admin.scss";
import "components/admin/create-new-ra";
import "components/admin/admin-manage-published-ra";
// import "components/admin/admin-online-ra";
import "components/admin/admin_dashboard";
import "components/admin/online-status-list";
import "components/admin/admin-confirm-winner";
import "components/admin/admin-report";
import "components/shared/check-network";
import "components/search/home-list";
import "components/admin/admin-invitation";
import "components/admin/admin-comsumption";
import "components/admin/admin-workflow";
import "components/admin/admin-buyer-dashboard";
import "components/admin/admin-buyer-list-detail";
//import "components/retailer/letter-of-award.jsx";
import "components/admin/admin-award";
import "components/admin/admin-choose-alternative-winner";
import "components/admin/admin-user-extends";
import "components/admin/admin-contact";
import "components/admin/admin-email-template";
import "components/admin/admin-common-template";
import "components/buyer/buyer-manage";
import "components/retailer/retailer-register";
import "components/admin/admin-expiry";
import "components/admin/admin-buyer-request";
// import "./javascripts/ajax-test.js";
//console.log("Admin Webpacker");

