apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: new-new-new-raweb-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - test-reverse-auction.southeastasia.cloudapp.azure.com
    secretName: my-new-tls-secret
  rules:
  - host: test-reverse-auction.southeastasia.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ra-web-service
          servicePort: 3000
